export class Array<T> {
    public length: int32;
    private arr: T[];
    
    init(arr: T[], length: int32) {
        this.length = length;
        this.arr = arr;
    }

    init(len: int32) {
        this.arr = T[len];
        this.length = len;
    }

    get(index: int32) : T {
        return this.arr[index];
    }

    insertAt(index: int32, value: T) : void {
        this.arr[index] = value;
    }
}
